package Hotel_managment;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.io.FileNotFoundException;
import java.io.File;
import java.io.FileReader;
import java.io.FilterWriter;
import javax.swing.JOptionPane;
import java.util.*;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;


/**
 *
 * @author hp
 */
public class chambre extends javax.swing.JFrame {

      String Nc,etag,nbr_lit,avec_tel,prix;
    FileWriter fw ;
    FileReader fr;
    int nbrc=0;
    File f,f1;
    RandomAccessFile raf,rafn;
    StringTokenizer st;
    chambre tclt[];
    String [][]dn;
    
   
    public chambre() {
        initComponents();
         jtbl.getTableHeader().setOpaque(false);
      jtbl.setBackground(Color.WHITE);
      jtbl.getTableHeader().setFont(new Font("calibri", Font.PLAIN, 20));
        jtbl.getTableHeader().setBackground(new Color(0, 96, 255));
        jtbl.getTableHeader().setForeground(new Color(255,255,255));
        
        jtbl.setRowHeight(40);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtetag1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl = new javax.swing.JTable();
        cmbnum = new javax.swing.JComboBox<>();
        txtetag = new javax.swing.JTextField();
        txtnbr_lit = new javax.swing.JTextField();
        txtavectv = new javax.swing.JTextField();
        txtprix = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtetag1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtetag1.setBorder(null);
        getContentPane().add(txtetag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 280, 28));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\menugenral\\back_enterd.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 60, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\save_leav.png")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 413, 62));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\recher_leav.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 413, 62));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\modi_leav.png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 413, 62));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\new_leav.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 413, 62));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\list_leav.png")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 413, 62));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\delet_leav.png")); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 413, 62));

        jtbl.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jtbl.setForeground(new java.awt.Color(153, 153, 153));
        jtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N de la chambre", "Etage", "N de lit", "avec une tele", "prix"
            }
        ));
        jtbl.setAlignmentX(0.9F);
        jtbl.setAlignmentY(1.0F);
        jtbl.setGridColor(new java.awt.Color(255, 255, 255));
        jtbl.setRowHeight(25);
        jtbl.setSelectionBackground(new java.awt.Color(255, 0, 116));
        jtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 310, 1090, 440));

        cmbnum.setEditable(true);
        cmbnum.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        cmbnum.setForeground(new java.awt.Color(153, 153, 153));
        cmbnum.setBorder(null);
        cmbnum.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbnumItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 30, 330, 50));

        txtetag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtetag.setBorder(null);
        getContentPane().add(txtetag, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 148, 280, 28));

        txtnbr_lit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnbr_lit.setBorder(null);
        getContentPane().add(txtnbr_lit, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 185, 280, 30));

        txtavectv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtavectv.setBorder(null);
        txtavectv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtavectvKeyPressed(evt);
            }
        });
        getContentPane().add(txtavectv, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 222, 280, 30));

        txtprix.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtprix.setBorder(null);
        getContentPane().add(txtprix, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 280, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\back77.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            lister();
            remplir();
           }catch(IOException e){}
    
    }//GEN-LAST:event_formWindowOpened

    private void cmbnumItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbnumItemStateChanged

    }//GEN-LAST:event_cmbnumItemStateChanged

    private void jtblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblMouseClicked

    }//GEN-LAST:event_jtblMouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\save_enterd.png"));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\save_leav.png"));
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        jLabel7.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\clicked\\save_click.png"));
        try{
            if(recherchercle()==false){
                enregistrer();
                remplir();
                JOptionPane.showMessageDialog(this, "le client est bien enregistré");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Le client existe déja");
                cmbnum.setSelectedItem(-1);
                cmbnum.requestFocus();
            }
        }catch(IOException |NullPointerException e){}
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\recher_enterd.png"));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\recher_leav.png"));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        jLabel2.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\clicked\\recher_click.png"));
        try{
            rechercher();
        }catch(IOException e){}
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel3.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\modi_enterd.png"));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\modi_leav.png"));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        jLabel3.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\clicked\\modi_click.png"));
        try{
            modifier();
        }catch(IOException e){}

    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\new_enterd.png"));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\new_leav.png"));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        jLabel4.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\clicked\\new_click.png"));
        Nouveau();
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\list_enterd.png"));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\list_leav.png"));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        jLabel5.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\clicked\\list_click.png"));

        try{
            lister();
        }catch(IOException e){}
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel6.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\delet_enterd.png"));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\delet_leav.png"));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        jLabel6.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\clicked\\delet_click.png"));

        try{
            supprimer();
        }catch(IOException e){}
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
         jLabel8.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\menugenral\\aaaaa.png"));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel8.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\menugenral\\back_enterd.png"));
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
         this.setVisible(false);
        new hotel_managment.menu_general().setVisible(true);
    }//GEN-LAST:event_jLabel8MousePressed

    private void txtavectvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtavectvKeyPressed
        if (evt.getKeyCode()=='\n'){
           if ((txtavectv.getText().compareTo("oui"))==0){
            txtprix.setText(String.valueOf(Integer.parseInt(txtnbr_lit.getText())*100+1000));
        }
           else if ((txtavectv.getText().compareTo("OUI"))==0){
            txtprix.setText(String.valueOf(Integer.parseInt(txtnbr_lit.getText())*100+1000));
        }
           else if ((txtavectv.getText().compareTo("Oui"))==0){
            txtprix.setText(String.valueOf(Integer.parseInt(txtnbr_lit.getText())*100+1000));
        }
           else{
               txtprix.setText(String.valueOf(Integer.parseInt(txtnbr_lit.getText())*100));
           }
          
        
    }
    }//GEN-LAST:event_txtavectvKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chambre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chambre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chambre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chambre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chambre().setVisible(true);
            }
        });
    }
    
    
    void Nouveau(){
        cmbnum.setSelectedIndex(-1); 
        txtetag.setText("");
        txtnbr_lit.setText("");
        txtavectv.setText("");
        txtprix.setText("");
        cmbnum.requestFocus();
}
    private void enregistrer()throws IOException {
        f=new File("D:\\MonDossier");
        if(!f.exists())
            f.mkdir();
        f1=new File(f,"ficherchambre.don");
	String line;
        line= txtetag1.getText()+'\t'+txtetag.getText()+'\t'+txtnbr_lit.getText()+'\t'+txtavectv.getText()+'\t'+txtprix.getText()+'\n';
        if( line.compareTo("")!=0){
            raf = new RandomAccessFile(f1, "rw");
            raf.seek(raf.length());
            raf.writeBytes(line);
            raf.close();
        }
    }
    private boolean recherchercle()throws IOException{
        String str,s;
        boolean bl=false;
        f=new File("D:\\MonDossier");
        if(!f.exists())
            f.mkdir();
            try{
                raf = new RandomAccessFile("D:\\MonDossier\\ficherchambre.don", "rw");
                if(raf.length()>0)
                while((str=raf.readLine())!=null){
                    if(str.trim().compareTo("")!=0){
                        st=new StringTokenizer(str,"\t");
                        s=String.valueOf(st.nextToken());
                        if(s.trim().compareTo(cmbnum.getSelectedItem().toString())==0)
                            bl=true;
                    }
                }
            }catch(IOException |NullPointerException |java.util.NoSuchElementException e){
            }finally{
                raf.close();
            }
        return bl;
    }
     private void rechercher()throws IOException{
        String str,s;
        try{
            raf = new RandomAccessFile("D:\\MonDossier\\ficherchambre.don", "rw");
            while((str=raf.readLine())!=null){
                if(str.trim().compareTo("")!=0){
                    st=new StringTokenizer(str,"\t");
                    s=String.valueOf(st.nextToken());
                    if(s.trim().compareTo(cmbnum.getSelectedItem().toString())==0){
                        txtetag1.setText(cmbnum.getSelectedItem().toString());
                        txtetag.setText(st.nextToken());
                        txtnbr_lit.setText(st.nextToken());
                        txtavectv.setText(st.nextToken());
                        txtprix.setText(st.nextToken());
                    }
                }    
            }
        }catch(IOException |NullPointerException |java.util.NoSuchElementException e){
        }finally{
            raf.close();
        }     
    }
    private void lister()throws IOException{
        String str="";
        try{
            raf = new RandomAccessFile("D:\\MonDossier\\ficherchambre.don", "rw");
            DefaultTableModel model = (DefaultTableModel) jtbl.getModel();
            while ( model.getRowCount()>0){
                model.removeRow(0);
            }
            while((str=raf.readLine())!=null){
                if(str.trim().compareTo("")!=0){
                    st=new StringTokenizer(str.trim(),"\t");
                    model.addRow(new Object[]{String.valueOf(st.nextToken()),String.valueOf(st.nextToken()),String.valueOf(st.nextToken()),String.valueOf(st.nextToken()),String.valueOf(st.nextToken())});
                }
            }
        }catch(IOException |NullPointerException |java.util.NoSuchElementException e){
        }finally{
            raf.close();
        }
    }
     private void remplir()throws IOException{
        String str="",titem[];
        int i=0,j;
        try{
            raf = new RandomAccessFile("D:\\MonDossier\\ficherchambre.don", "rw");
            while((str=raf.readLine())!=null){
                if(str.trim().compareTo("")!=0) 
                i++;
            }
         }catch(IOException |NullPointerException e){
        }finally{
            raf.close();
        }
        //raf.close();
        titem=new String[i];
        j=0;
        try{
            raf = new RandomAccessFile("D:\\MonDossier\\ficherchambre.don", "rw");
            while((str=raf.readLine())!=null){
                if(str.trim().compareTo("")!=0){
                    st=new StringTokenizer(str.trim(),"\t");
                    titem[j]=String.valueOf(st.nextToken());
                    j++;
                }
            }
        }catch(IOException |NullPointerException |java.util.NoSuchElementException e){
        }finally{
            raf.close();
        }
        cmbnum.setModel(new javax.swing.DefaultComboBoxModel<>(titem));
    }
    private void modifier()throws IOException{
        String str,s;
        f=new File("D:\\MonDossier\\ficherchambre.don.don");
        int nbrenr=0;
        try{
            raf = new RandomAccessFile(f, "rw");
            while((str=raf.readLine())!=null)
                if(str.trim().compareTo("")!=0)
                    nbrenr++;
        }catch(IOException |NullPointerException e){
        }finally{
            raf.close();
        }
        if(nbrenr>0){
            dn=new String[nbrenr][5];
            int i=0;
            try{
                raf = new RandomAccessFile(f, "rw");
                while((str=raf.readLine())!=null){
                    if(str.trim().compareTo("")!=0){
                        st=new StringTokenizer(str,"\t");
                        s=st.nextToken();
                        if(s.trim().compareTo(cmbnum.getSelectedItem().toString().trim())!=0){
                            dn[i][0]=s+'\t';
                            dn[i][1]=String.valueOf(st.nextToken())+'\t';
                            dn[i][2]=String.valueOf(st.nextToken())+'\t';
                            dn[i][3]=String.valueOf(st.nextToken())+'\t';
                            dn[i][4]=String.valueOf(st.nextToken())+'\n';
                        }
                        else{
                            dn[i][0]=cmbnum.getSelectedItem().toString()+'\t';
                            dn[i][1]=txtetag.getText()+'\t';
                            dn[i][2]=txtnbr_lit.getText()+'\t';
                            dn[i][3]=txtavectv.getText()+'\t';
                            dn[i][4]=txtprix.getText()+'\n';
                        }
                    i++;
                }
            }
        }catch(IOException |NullPointerException |java.util.NoSuchElementException e){
        }finally{
            raf.close();
        }   
        int choix = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment modifier cet enregistrement?", "Modifier", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(choix==JOptionPane.YES_OPTION){
            String line;
            f=new File("D:\\MonDossier");
            if(!f.exists())
                f.mkdir();
            f1=new File(f,"ficherchambre.don");
            try{
                f1.delete();
            } catch (Exception ex) {
                System.out.println("Erreur: "+ex.getMessage());
            }
            f1=new File(f,"ficherchambre.don");
            
            //for(int j=0;j<dn[0].length;j++){
              //  line= dn[j][0]+dn[j][1]+dn[j][2]+dn[j][3]+ dn[j][4];
            for (String[] dn1 : dn) {
                line = dn1[0] + dn1[1] + dn1[2] + dn1[3] + dn1[4];
                if( line.compareTo("")!=0 && dn1!=null){ 
                    try{
                        raf = new RandomAccessFile(f1, "rw");
                        raf.seek(raf.length());
                        raf.writeBytes(line);                    
                    }catch(IOException |NullPointerException e){
                    }finally{
                        raf.close();
                    }
                }
            }
        }
     }
    }

    private void supprimer()throws IOException{
        String str,s;
        f=new File("D:\\MonDossier\\ficherchambre.don");
        int nbrenr=0;
        try{
            raf = new RandomAccessFile(f, "rw");
            while((str=raf.readLine())!=null)
                if(str.trim().compareTo("")!=0){
                    st=new StringTokenizer(str,"\t");
                    s=st.nextToken();
                    if(s.trim().compareTo(cmbnum.getSelectedItem().toString())!=0){
                        nbrenr++;
                    }
                } 
        }catch(IOException |NullPointerException e){
        }finally{
            raf.close();
        }
        if(nbrenr>0){
            dn=new String[nbrenr][5];
            int i=0;
            try{
                raf = new RandomAccessFile(f, "rw");
                while((str=raf.readLine())!=null){
                    if(str.trim().compareTo("")!=0){
                        st=new StringTokenizer(str,"\t");
                        s=st.nextToken();
                        if(s.trim().compareTo(cmbnum.getSelectedItem().toString())!=0){
                            dn[i][0]=s+'\t';
                            dn[i][1]=String.valueOf(st.nextToken())+'\t';
                            dn[i][2]=String.valueOf(st.nextToken())+'\t';
                            dn[i][3]=String.valueOf(st.nextToken())+'\t';
                            dn[i][4]=String.valueOf(st.nextToken())+'\n';
                            i++;
                        }
                }
            }
        }catch(IOException |NullPointerException |java.util.NoSuchElementException e){
        }finally{
            raf.close();
        }   
        int choix = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer cet enregistrement?", "Suppression", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(choix==JOptionPane.YES_OPTION){
            String line;
            f=new File("D:\\MonDossier");
            if(!f.exists())
                f.mkdir();
            f1=new File(f,"ficherchambre.don");
            try{
                f1.delete();
            } catch (Exception ex) {
                System.out.println("Erreur: "+ex.getMessage());
            }
            //f1.delete();
            f1=new File(f,"ficherchambre.don");
            
            //for(int j=0;j<dn[0].length;j++){
              //  line= dn[j][0]+dn[j][1]+dn[j][2]+dn[j][3]+ dn[j][4];
            for (String[] dn1 : dn) {
                line = dn1[0] + dn1[1] + dn1[2] + dn1[3] + dn1[4];
                if( line.compareTo("")!=0 && dn1!=null){ 
                    try{
                        raf = new RandomAccessFile(f1, "rw");
                        raf.seek(raf.length());
                        raf.writeBytes(line);                    
                    }catch(IOException |NullPointerException e){
                    }finally{
                        raf.close();
                    }
                }
            }
        }
     }
    }
     private void afficherligne(){
        cmbnum.setSelectedItem(jtbl.getValueAt(jtbl.getSelectedRow(), 0).toString());
        txtetag.setText(jtbl.getValueAt(jtbl.getSelectedRow(), 1).toString());
        txtnbr_lit.setText(jtbl.getValueAt(jtbl.getSelectedRow(), 2).toString());
        txtavectv.setText(jtbl.getValueAt(jtbl.getSelectedRow(), 3).toString());
        txtprix.setText(jtbl.getValueAt(jtbl.getSelectedRow(), 4).toString());  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbnum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbl;
    private javax.swing.JTextField txtavectv;
    private javax.swing.JTextField txtetag;
    private javax.swing.JTextField txtetag1;
    private javax.swing.JTextField txtnbr_lit;
    private javax.swing.JTextField txtprix;
    // End of variables declaration//GEN-END:variables
}
