package Hotel_managment;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.io.FileNotFoundException;
import java.io.File;
import java.io.FileReader;
import java.io.FilterWriter;
import javax.swing.JOptionPane;
import java.util.*;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;

/**
 *
 * @author hp
 */
public class reservation extends javax.swing.JFrame {
      String Nc_res,etag_res,nbr_lit_res,avec_tel_res,prix_res,NM_res,nom_res,prn_res,adr_res,tel_res,dure,tot;
    FileWriter fw ;
    FileReader fr;
    int nbrc=0;
    File f,f1;
    RandomAccessFile raf,rafn;
    StringTokenizer st;
    chambre tclt[];
    String [][]dn;
    
    public reservation() {
        initComponents();
       jtbl.getTableHeader().setOpaque(false);
      jtbl.setBackground(Color.WHITE);
      jtbl.getTableHeader().setFont(new Font("calibri", Font.PLAIN, 20));
        jtbl.getTableHeader().setBackground(new Color(0, 96, 255));
        jtbl.getTableHeader().setForeground(new Color(255,255,255));
        
        jtbl.setRowHeight(40);
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        txt_durrer = new javax.swing.JTextField();
        txt_tot = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtprn = new javax.swing.JTextField();
        cmbnum = new javax.swing.JComboBox<>();
        txtadr = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        cmbnum1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl = new javax.swing.JTable();
        txtetag = new javax.swing.JTextField();
        txtprix = new javax.swing.JTextField();
        txtnbr_lit = new javax.swing.JTextField();
        txtavectv = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\menugenral\\back_enterd.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 60, 50));

        txt_durrer.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txt_durrer.setForeground(new java.awt.Color(153, 153, 153));
        txt_durrer.setBorder(null);
        txt_durrer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_durrerKeyPressed(evt);
            }
        });
        getContentPane().add(txt_durrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 270, 250, 30));

        txt_tot.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txt_tot.setForeground(new java.awt.Color(153, 153, 153));
        txt_tot.setBorder(null);
        getContentPane().add(txt_tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 310, 250, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\save_leav.png")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 330, 62));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\recher_leav.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 330, 62));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\list_leav.png")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 330, 62));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\new_leav.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 330, 62));

        txtnom.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtnom.setForeground(new java.awt.Color(153, 153, 153));
        txtnom.setBorder(null);
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 200, 30));

        txtprn.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtprn.setForeground(new java.awt.Color(153, 153, 153));
        txtprn.setBorder(null);
        getContentPane().add(txtprn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 200, 30));

        cmbnum.setEditable(true);
        cmbnum.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        cmbnum.setForeground(new java.awt.Color(153, 153, 153));
        cmbnum.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbnumItemStateChanged(evt);
            }
        });
        cmbnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbnumActionPerformed(evt);
            }
        });
        getContentPane().add(cmbnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 310, 50));

        txtadr.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtadr.setForeground(new java.awt.Color(153, 153, 153));
        txtadr.setBorder(null);
        getContentPane().add(txtadr, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 200, 30));

        txtTel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtTel.setForeground(new java.awt.Color(153, 153, 153));
        txtTel.setBorder(null);
        getContentPane().add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 200, 30));

        cmbnum1.setEditable(true);
        cmbnum1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        cmbnum1.setForeground(new java.awt.Color(153, 153, 153));
        cmbnum1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbnum1ItemStateChanged(evt);
            }
        });
        cmbnum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbnum1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbnum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, 330, 50));

        jtbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jtbl.setForeground(new java.awt.Color(153, 153, 153));
        jtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N de chambre", "etage", "N de lit", "avec une tele", "prix", "Numero", "Nom client", "Prenom", "Adresse", "Téléphon", "durer", "total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl.setGridColor(new java.awt.Color(255, 255, 255));
        jtbl.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jtbl.setOpaque(false);
        jtbl.setRowHeight(25);
        jtbl.setSelectionBackground(new java.awt.Color(255, 0, 116));
        jtbl.setShowVerticalLines(false);
        jtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 370, 1160, 330));

        txtetag.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtetag.setForeground(new java.awt.Color(153, 153, 153));
        txtetag.setBorder(null);
        getContentPane().add(txtetag, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 90, 250, 30));

        txtprix.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtprix.setForeground(new java.awt.Color(153, 153, 153));
        txtprix.setBorder(null);
        getContentPane().add(txtprix, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 220, 250, 30));

        txtnbr_lit.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtnbr_lit.setForeground(new java.awt.Color(153, 153, 153));
        txtnbr_lit.setBorder(null);
        getContentPane().add(txtnbr_lit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 130, 250, 30));

        txtavectv.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtavectv.setForeground(new java.awt.Color(153, 153, 153));
        txtavectv.setBorder(null);
        getContentPane().add(txtavectv, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 180, 250, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\backiiiiiiii.png")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbnumItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbnumItemStateChanged
       try{
            rechercher();
        }catch(IOException e){}
    }//GEN-LAST:event_cmbnumItemStateChanged

    private void cmbnum1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbnum1ItemStateChanged
           try{
            rechercher_chm();
        }catch(IOException e){}
    }//GEN-LAST:event_cmbnum1ItemStateChanged

    private void jtblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblMouseClicked

    }//GEN-LAST:event_jtblMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            lister();
            remplir_cl();
            remplir_chm();
           }catch(IOException e){}
                         

    }//GEN-LAST:event_formWindowOpened

    private void cmbnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbnumActionPerformed
          try{
            rechercher();
        }catch(IOException e){}
    }//GEN-LAST:event_cmbnumActionPerformed

    private void cmbnum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbnum1ActionPerformed
         try{
            rechercher_chm();
        }catch(IOException e){}
    }//GEN-LAST:event_cmbnum1ActionPerformed

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\save_enterd.png"));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\save_leav.png"));
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        jLabel7.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\clicked\\save_click.png"));
        try{
            
                enregistrer();
                
                JOptionPane.showMessageDialog(this, "la reservation est bien effectuer");
            
            
        }catch(IOException |NullPointerException e){}
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\recher_enterd.png"));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\recher_leav.png"));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        jLabel2.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\clicked\\recher_click.png"));
        try{
            rechercher();
        }catch(IOException e){}
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\list_enterd.png"));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\list_leav.png"));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        jLabel5.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\clicked\\list_click.png"));

        try{
            lister();
        }catch(IOException e){}
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\new_enterd.png"));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\new_leav.png"));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        jLabel4.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\clicked\\new_click.png"));
        Nouveau();
    }//GEN-LAST:event_jLabel4MousePressed

    private void txt_durrerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_durrerKeyPressed
        if (evt.getKeyCode()=='\n'){
            int a =0;
            int b=0;
            int c =0;
            a = (Integer.parseInt(txtprix.getText()));
            b = (Integer.parseInt(txt_durrer.getText()));
            c = a*b;
            txt_tot.setText(String.valueOf(c));
        
    }
    }//GEN-LAST:event_txt_durrerKeyPressed

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel8.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\menugenral\\aaaaa.png"));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel8.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\menugenral\\back_enterd.png"));
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        this.setVisible(false);
        new hotel_managment.menu_general().setVisible(true);
    }//GEN-LAST:event_jLabel8MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reservation().setVisible(true);
            }
        });
    }
    private void remplir_chm()throws IOException{
        String str="",titem[];
        int i=0,j;
        try{
            raf = new RandomAccessFile("D:\\MonDossier\\ficherchambre.don", "rw");
            while((str=raf.readLine())!=null){
                if(str.trim().compareTo("")!=0) 
                i++;
            }
         }catch(IOException |NullPointerException e){
        }finally{
            raf.close();
        }
        //raf.close();
        titem=new String[i];
        j=0;
        try{
            raf = new RandomAccessFile("D:\\MonDossier\\ficherchambre.don", "rw");
            while((str=raf.readLine())!=null){
                if(str.trim().compareTo("")!=0){
                    st=new StringTokenizer(str.trim(),"\t");
                    titem[j]=String.valueOf(st.nextToken());
                    j++;
                }
            }
        }catch(IOException |NullPointerException |java.util.NoSuchElementException e){
        }finally{
            raf.close();
        }
        cmbnum1.setModel(new javax.swing.DefaultComboBoxModel<>(titem));
    }
    private void remplir_cl()throws IOException{
        String str="",titem[];
        int i=0,j;
        try{
            raf = new RandomAccessFile("D:\\MonDossier\\fichierClient.don", "rw");
            while((str=raf.readLine())!=null){
                if(str.trim().compareTo("")!=0) 
                i++;
            }
         }catch(IOException |NullPointerException e){
        }finally{
            raf.close();
        }
        //raf.close();
        titem=new String[i];
        j=0;
        try{
            raf = new RandomAccessFile("D:\\MonDossier\\fichierClient.don", "rw");
            while((str=raf.readLine())!=null){
                if(str.trim().compareTo("")!=0){
                    st=new StringTokenizer(str.trim(),"\t");
                    titem[j]=String.valueOf(st.nextToken());
                    j++;
                }
            }
        }catch(IOException |NullPointerException |java.util.NoSuchElementException e){
        }finally{
            raf.close();
        }
        cmbnum.setModel(new javax.swing.DefaultComboBoxModel<>(titem));
    }
    void Nouveau(){
        cmbnum.setSelectedIndex(-1); 
        txtnom.setText("");
        txtprn.setText("");
        txtadr.setText("");
        txtTel.setText("");
        
        txtetag.setText("");
        txtnbr_lit.setText("");
        txtavectv.setText("");
        txtprix.setText("");
        cmbnum.requestFocus();
}
    
    private void enregistrer()throws IOException {
        f=new File("D:\\MonDossier");
        if(!f.exists())
            f.mkdir();
        f1=new File(f,"fichierreservation.don");
	String line;
       
   
        line= cmbnum1.getSelectedItem().toString()+'\t'+txtetag.getText()+'\t'+txtnbr_lit.getText()+'\t'+txtavectv.getText()+'\t'+txtprix.getText()+'\t'+cmbnum.getSelectedItem().toString()+'\t'+txtnom.getText()+'\t'+txtprn.getText()+'\t'+txtadr.getText()+'\t'+txtTel.getText()+'\t'+txt_durrer.getText()+'\t'+txt_tot.getText()+'\n';
   
        if( line.compareTo("")!=0){
            raf = new RandomAccessFile(f1, "rw");
            raf.seek(raf.length());
            raf.writeBytes(line);
            raf.close();
        }
    }
    private boolean rechercher_chm_val()throws IOException{
        String str,s;
        boolean bl=false;
        f=new File("D:\\MonDossier");
        if(!f.exists())
            f.mkdir();
            try{
                raf = new RandomAccessFile("D:\\MonDossier\\fichierreservation.don", "rw");
                if(raf.length()>0)
                while((str=raf.readLine())!=null){
                    if(str.trim().compareTo("")!=0){
                        st=new StringTokenizer(str,"\t");
                        s=String.valueOf(st.nextToken());
                        if(s.trim().compareTo(cmbnum1.getSelectedItem().toString())==0)
                            bl=true;
                    }
                }
            }catch(IOException |NullPointerException |java.util.NoSuchElementException e){
            }finally{
                raf.close();
            }
        return bl;
    }
    private void lister()throws IOException{
        String str="";
        try{
            raf = new RandomAccessFile("D:\\MonDossier\\fichierreservation.don", "rw");
            DefaultTableModel model = (DefaultTableModel) jtbl.getModel();
            while ( model.getRowCount()>0){
                model.removeRow(0);
            }
            while((str=raf.readLine())!=null){
                if(str.trim().compareTo("")!=0){
                    st=new StringTokenizer(str.trim(),"\t");
                    model.addRow(new Object[]{String.valueOf(st.nextToken()),String.valueOf(st.nextToken()),String.valueOf(st.nextToken()),String.valueOf(st.nextToken()),String.valueOf(st.nextToken()),String.valueOf(st.nextToken()),String.valueOf(st.nextToken()),String.valueOf(st.nextToken()),String.valueOf(st.nextToken()),String.valueOf(st.nextToken()),String.valueOf(st.nextToken()),String.valueOf(st.nextToken())});
                   
                }
            }
        }catch(IOException |NullPointerException |java.util.NoSuchElementException e){
           
        }finally{
            raf.close();
           
        }
    }
    private boolean recherchercle()throws IOException{
        String str,s;
        boolean bl=false;
        f=new File("D:\\MonDossier");
        if(!f.exists())
            f.mkdir();
            try{
                raf = new RandomAccessFile("D:\\MonDossier\\fichierreservation.don", "rw");
                if(raf.length()>0)
                while((str=raf.readLine())!=null){
                    if(str.trim().compareTo("")!=0){
                        st=new StringTokenizer(str,"\t");
                        s=String.valueOf(st.nextToken());
                        if(s.trim().compareTo(cmbnum.getSelectedItem().toString())==0)
                            bl=true;
                    }
                }
            }catch(IOException |NullPointerException |java.util.NoSuchElementException e){
            }finally{
                raf.close();
            }
        return bl;
    }
     private void rechercher()throws IOException{
        String str,s;
        try{
            raf = new RandomAccessFile("D:\\MonDossier\\fichierClient.don", "rw");
            while((str=raf.readLine())!=null){
                if(str.trim().compareTo("")!=0){
                    st=new StringTokenizer(str,"\t");
                    s=String.valueOf(st.nextToken());
                    if(s.trim().compareTo(cmbnum.getSelectedItem().toString())==0){
                        txtnom.setText(st.nextToken());
                        txtprn.setText(st.nextToken());
                        txtadr.setText(st.nextToken());
                        txtTel.setText(st.nextToken());
                    }
                }    
            }
        }catch(IOException |NullPointerException |java.util.NoSuchElementException e){
        }finally{
            raf.close();
        }     
    }
     
    
      private void rechercher_chm()throws IOException{
        String str,s;
        try{
            raf = new RandomAccessFile("D:\\MonDossier\\ficherchambre.don", "rw");
            while((str=raf.readLine())!=null){
                if(str.trim().compareTo("")!=0){
                    st=new StringTokenizer(str,"\t");
                    s=String.valueOf(st.nextToken());
                    if(s.trim().compareTo(cmbnum1.getSelectedItem().toString())==0){
                        txtetag.setText(st.nextToken());
                        txtnbr_lit.setText(st.nextToken());
                        txtavectv.setText(st.nextToken());
                        txtprix.setText(st.nextToken());
                    }
                }    
            }
        }catch(IOException |NullPointerException |java.util.NoSuchElementException e){
        }finally{
            raf.close();
        }     
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbnum;
    private javax.swing.JComboBox<String> cmbnum1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbl;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txt_durrer;
    private javax.swing.JTextField txt_tot;
    private javax.swing.JTextField txtadr;
    private javax.swing.JTextField txtavectv;
    private javax.swing.JTextField txtetag;
    private javax.swing.JTextField txtnbr_lit;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprix;
    private javax.swing.JTextField txtprn;
    // End of variables declaration//GEN-END:variables
}
