/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_managment;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.io.FileNotFoundException;
import java.io.File;
import java.io.FileReader;
import java.io.FilterWriter;
import javax.swing.JOptionPane;
import java.util.*;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.border.*;
/**
 *
 * @author hp
 */
public class user_interface extends javax.swing.JFrame {
     String nom,email1,adress1,phon,motdepass;
    FileWriter fw ;
    FileReader fr;
    int nbrc=0;
    File f,f1;
    RandomAccessFile raf,rafn;
    StringTokenizer st;
    Hotel_managment.client tclt[];
    String [][]dn;
    /**
     * Creates new form user_interface
     */
    public user_interface() {
        initComponents();
        
        jtbl.getTableHeader().setOpaque(false);
      jtbl.setBackground(Color.WHITE);
      jtbl.getTableHeader().setFont(new Font("calibri", Font.PLAIN, 20));
        jtbl.getTableHeader().setBackground(new Color(0, 96, 255));
        jtbl.getTableHeader().setForeground(new Color(255,255,255));
        
        jtbl.setRowHeight(40);
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl = new javax.swing.JTable();
        cmbnum = new javax.swing.JComboBox<>();
        jPasswordField1 = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        emaillll = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        adress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1480, 740));
        setSize(new java.awt.Dimension(1480, 740));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\menugenral\\back_enterd.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 60, 50));

        jtbl.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jtbl.setForeground(new java.awt.Color(204, 204, 204));
        jtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom ", "email", "adress", "telephone", "mot de pass"
            }
        ));
        jtbl.setAlignmentX(0.9F);
        jtbl.setAlignmentY(1.0F);
        jtbl.setGridColor(new java.awt.Color(255, 255, 255));
        jtbl.setRowHeight(25);
        jtbl.setSelectionBackground(new java.awt.Color(255, 0, 116));
        jtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 260, 1070, 490));

        cmbnum.setEditable(true);
        cmbnum.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        cmbnum.setForeground(new java.awt.Color(153, 153, 153));
        cmbnum.setBorder(null);
        cmbnum.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbnumItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 30, 330, 50));

        jPasswordField1.setFont(new java.awt.Font("OCR A Extended", 0, 20)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordField1.setBorder(null);
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 180, 240, 30));

        username.setFont(new java.awt.Font("OCR A Extended", 0, 20)); // NOI18N
        username.setForeground(new java.awt.Color(102, 102, 102));
        username.setBorder(null);
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 240, 30));

        emaillll.setFont(new java.awt.Font("OCR A Extended", 0, 20)); // NOI18N
        emaillll.setForeground(new java.awt.Color(102, 102, 102));
        emaillll.setBorder(null);
        getContentPane().add(emaillll, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 240, 30));

        phone.setFont(new java.awt.Font("OCR A Extended", 0, 20)); // NOI18N
        phone.setForeground(new java.awt.Color(102, 102, 102));
        phone.setBorder(null);
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 240, 30));

        adress.setFont(new java.awt.Font("OCR A Extended", 0, 20)); // NOI18N
        adress.setForeground(new java.awt.Color(102, 102, 102));
        adress.setBorder(null);
        getContentPane().add(adress, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 240, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\save_leav.png")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 413, 62));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\recher_leav.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 413, 62));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\modi_leav.png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 413, 62));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\new_leav.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 413, 62));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\list_leav.png")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 413, 62));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\delet_leav.png")); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 413, 62));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\backuser_inter.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\save_enterd.png"));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\save_leav.png"));
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        jLabel7.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\clicked\\save_click.png"));
        try{
            if(recherchercle()==false){
                enregistrer();
                remplir();
                JOptionPane.showMessageDialog(this, "le client est bien enregistré");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Le client existe déja");
                cmbnum.setSelectedItem(-1);
                cmbnum.requestFocus();
            }
        }catch(IOException |NullPointerException e){}
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\recher_enterd.png"));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\recher_leav.png"));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        jLabel2.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\clicked\\recher_click.png"));
        try{
            rechercher();
        }catch(IOException e){}
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel3.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\modi_enterd.png"));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\modi_leav.png"));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        jLabel3.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\clicked\\modi_click.png"));
        try{
            modifier();
        }catch(IOException e){}

    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\new_enterd.png"));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\new_leav.png"));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        jLabel4.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\clicked\\new_click.png"));
       
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\list_enterd.png"));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\list_leav.png"));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        jLabel5.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\clicked\\list_click.png"));

        try{
            lister();
        }catch(IOException e){}
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel6.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\delet_enterd.png"));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\DDDDDD\\delet_leav.png"));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        jLabel6.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\hover_effact\\newhe\\clicked\\delet_click.png"));

        try{
            supprimer();
        }catch(IOException e){}
    }//GEN-LAST:event_jLabel6MousePressed

    private void cmbnumItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbnumItemStateChanged

    }//GEN-LAST:event_cmbnumItemStateChanged

    private void jtblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblMouseClicked

    }//GEN-LAST:event_jtblMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            lister();
            remplir();
           }catch(IOException e){}
    }//GEN-LAST:event_formWindowOpened

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel8.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\menugenral\\aaaaa.png"));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel8.setIcon(new ImageIcon("C:\\Users\\hp\\Desktop\\POROGET_JAVA\\menugenral\\back_enterd.png"));
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        this.setVisible(false);
        new hotel_managment.menu_general().setVisible(true);
    }//GEN-LAST:event_jLabel8MousePressed
    private void enregistrer()throws IOException {
        f=new File("D:\\MonDossier");
        if(!f.exists())
            f.mkdir();
        f1=new File(f,"fichierusers.don");
	String line;
        line= username.getText()+'\t'+emaillll.getText()+'\t'+adress.getText()+'\t'+phone.getText()+'\t'+jPasswordField1.getText()+'\n';
        if( line.compareTo("")!=0){
            raf = new RandomAccessFile(f1, "rw");
            raf.seek(raf.length());
            raf.writeBytes(line);
            raf.close();
        }
    }
     private boolean recherchercle()throws IOException{
        String str,s;
        boolean bl=false;
        f=new File("D:\\MonDossier");
        if(!f.exists())
            f.mkdir();
            try{
                raf = new RandomAccessFile("D:\\MonDossier\\fichierusers.don", "rw");
                if(raf.length()>0)
                while((str=raf.readLine())!=null){
                    if(str.trim().compareTo("")!=0){
                        st=new StringTokenizer(str,"\t");
                        s=String.valueOf(st.nextToken());
                        if(s.trim().compareTo(username.getText())==0)
                            bl=true;
                    }
                }
            }catch(IOException |NullPointerException |java.util.NoSuchElementException e){
            }finally{
                raf.close();
            }
        return bl;
    }
     private void rechercher()throws IOException{
        String str,s;
        try{
            raf = new RandomAccessFile("D:\\MonDossier\\fichierusers.don", "rw");
            while((str=raf.readLine())!=null){
                if(str.trim().compareTo("")!=0){
                    st=new StringTokenizer(str,"\t"); 
                    s=String.valueOf(st.nextToken());
                    if(s.trim().compareTo(cmbnum.getSelectedItem().toString())==0){
                        
                        username.setText((cmbnum.getSelectedItem().toString()));
                        emaillll.setText(st.nextToken());
                        adress.setText(st.nextToken());
                        phone.setText(st.nextToken());
                        jPasswordField1.setText(st.nextToken());
                    }
                }    
            }
        }catch(IOException |NullPointerException |java.util.NoSuchElementException e){
        }finally{
            raf.close();
        }     
    }
    private void lister()throws IOException{
        String str="";
        try{
            raf = new RandomAccessFile("D:\\MonDossier\\fichierusers.don", "rw");
            DefaultTableModel model = (DefaultTableModel) jtbl.getModel();
            while ( model.getRowCount()>0){
                model.removeRow(0);
            }
            while((str=raf.readLine())!=null){
                if(str.trim().compareTo("")!=0){
                    st=new StringTokenizer(str.trim(),"\t");
                    model.addRow(new Object[]{String.valueOf(st.nextToken()),String.valueOf(st.nextToken()),String.valueOf(st.nextToken()),String.valueOf(st.nextToken()),String.valueOf(st.nextToken())});
                }
            }
        }catch(IOException |NullPointerException |java.util.NoSuchElementException e){
        }finally{
            raf.close();
        }
    }
     private void remplir()throws IOException{
        String str="",titem[];
        int i=0,j;
        try{
            raf = new RandomAccessFile("D:\\MonDossier\\fichierusers.don", "rw");
            while((str=raf.readLine())!=null){
                if(str.trim().compareTo("")!=0) 
                i++;
            }
         }catch(IOException |NullPointerException e){
        }finally{
            raf.close();
        }
        //raf.close();
        titem=new String[i];
        j=0;
        try{
            raf = new RandomAccessFile("D:\\MonDossier\\fichierusers.don", "rw");
            while((str=raf.readLine())!=null){
                if(str.trim().compareTo("")!=0){
                    st=new StringTokenizer(str.trim(),"\t");
                    titem[j]=String.valueOf(st.nextToken());
                    j++;
                }
            }
        }catch(IOException |NullPointerException |java.util.NoSuchElementException e){
        }finally{
            raf.close();
        }
        cmbnum.setModel(new javax.swing.DefaultComboBoxModel<>(titem));
    }
    private void modifier()throws IOException{
        String str,s;
        f=new File("D:\\MonDossier\\fichierusers.don");
        int nbrenr=0;
        try{
            raf = new RandomAccessFile(f, "rw");
            while((str=raf.readLine())!=null)
                if(str.trim().compareTo("")!=0)
                    nbrenr++;
        }catch(IOException |NullPointerException e){
        }finally{
            raf.close();
        }
        if(nbrenr>0){
            dn=new String[nbrenr][5];
            int i=0;
            try{
                raf = new RandomAccessFile(f, "rw");
                while((str=raf.readLine())!=null){
                    if(str.trim().compareTo("")!=0){
                        st=new StringTokenizer(str,"\t");
                        s=st.nextToken();
                        if(s.trim().compareTo(cmbnum.getSelectedItem().toString().trim())!=0){
                            dn[i][0]=s+'\t';
                            dn[i][1]=String.valueOf(st.nextToken())+'\t';
                            dn[i][2]=String.valueOf(st.nextToken())+'\t';
                            dn[i][3]=String.valueOf(st.nextToken())+'\t';
                            dn[i][4]=String.valueOf(st.nextToken())+'\n';
                        }
                        else{
                            dn[i][0]=username.getText()+'\t';
                            dn[i][1]=emaillll.getText()+'\t';
                            dn[i][2]=adress.getText()+'\t';
                            dn[i][3]=phone.getText()+'\t';
                            dn[i][4]=jPasswordField1.getText()+'\n';
                        }
                    i++;
                }
            }
        }catch(IOException |NullPointerException |java.util.NoSuchElementException e){
        }finally{
            raf.close();
        }   
        int choix = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment modifier cet enregistrement?", "Modifier", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(choix==JOptionPane.YES_OPTION){
            String line;
            f=new File("D:\\MonDossier");
            if(!f.exists())
                f.mkdir();
            f1=new File(f,"fichierusers.don");
            try{
                f1.delete();
            } catch (Exception ex) {
                System.out.println("Erreur: "+ex.getMessage());
            }
            f1=new File(f,"fichierusers.don");
            
            //for(int j=0;j<dn[0].length;j++){
              //  line= dn[j][0]+dn[j][1]+dn[j][2]+dn[j][3]+ dn[j][4];
            for (String[] dn1 : dn) {
                line = dn1[0] + dn1[1] + dn1[2] + dn1[3] + dn1[4];
                if( line.compareTo("")!=0 && dn1!=null){ 
                    try{
                        raf = new RandomAccessFile(f1, "rw");
                        raf.seek(raf.length());
                        raf.writeBytes(line);                    
                    }catch(IOException |NullPointerException e){
                    }finally{
                        raf.close();
                    }
                }
            }
        }
     }
    }

    

    private void supprimer()throws IOException{
        String str,s;
        f=new File("D:\\MonDossier\\fichierusers.don");
        int nbrenr=0;
        try{
            raf = new RandomAccessFile(f, "rw");
            while((str=raf.readLine())!=null)
                if(str.trim().compareTo("")!=0){
                    st=new StringTokenizer(str,"\t");
                    s=st.nextToken();
                    if(s.trim().compareTo(cmbnum.getSelectedItem().toString())!=0){
                        nbrenr++;
                    }
                } 
        }catch(IOException |NullPointerException e){
        }finally{
            raf.close();
        }
        if(nbrenr>0){
            dn=new String[nbrenr][5];
            int i=0;
            try{
                raf = new RandomAccessFile(f, "rw");
                while((str=raf.readLine())!=null){
                    if(str.trim().compareTo("")!=0){
                        st=new StringTokenizer(str,"\t");
                        s=st.nextToken();
                        if(s.trim().compareTo(cmbnum.getSelectedItem().toString())!=0){
                            dn[i][0]=s+'\t';
                            dn[i][1]=String.valueOf(st.nextToken())+'\t';
                            dn[i][2]=String.valueOf(st.nextToken())+'\t';
                            dn[i][3]=String.valueOf(st.nextToken())+'\t';
                            dn[i][4]=String.valueOf(st.nextToken())+'\n';
                            i++;
                        }
                }
            }
        }catch(IOException |NullPointerException |java.util.NoSuchElementException e){
        }finally{
            raf.close();
        }   
        int choix = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer cet enregistrement?", "Suppression", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(choix==JOptionPane.YES_OPTION){
            String line;
            f=new File("D:\\MonDossier");
            if(!f.exists())
                f.mkdir();
            f1=new File(f,"fichierusers.don");
            try{
                f1.delete();
            } catch (Exception ex) {
                System.out.println("Erreur: "+ex.getMessage());
            }
            //f1.delete();
            f1=new File(f,"fichierusers.don");
            
            //for(int j=0;j<dn[0].length;j++){
              //  line= dn[j][0]+dn[j][1]+dn[j][2]+dn[j][3]+ dn[j][4];
            for (String[] dn1 : dn) {
                line = dn1[0] + dn1[1] + dn1[2] + dn1[3] + dn1[4];
                if( line.compareTo("")!=0 && dn1!=null){ 
                    try{
                        raf = new RandomAccessFile(f1, "rw");
                        raf.seek(raf.length());
                        raf.writeBytes(line);                    
                    }catch(IOException |NullPointerException e){
                    }finally{
                        raf.close();
                    }
                }
            }
        }
     }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adress;
    private javax.swing.JComboBox<String> cmbnum;
    private javax.swing.JTextField emaillll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbl;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
